config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'

  get 'content_items/search'
  post 'content_items/search'
  get 'content_items/show'
  get 'users/public_notes'
  get     'help'      => 'static_pages#help'
  get     'signup'    => 'users#new'
  get     'login'     => 'sessions#new'
  post    'login'     => 'sessions#create'
  delete  'logout'    => 'sessions#destroy'

  resources :users
  resources :notes
  

 
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user

	validates :title, presence: true
	validates :content_item_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
  has_many :notes

	before_save { email.downcase! }

	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates  :email, presence: true, length: {maximum: 255}, 
			   		   format: { with: VALID_EMAIL_REGEX},
			   		   uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}


	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  def authenticated?(remember_token)
  	 return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
  	update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include NotesHelper
end

app/controllers/content_items_controller.rb
class ContentItemsController < ApplicationController
	protect_from_forgery unless: -> { request.format.json? }
	#for: Can't verify CSRF token authenticity
	skip_before_filter  :verify_authenticity_token

  def search
   # so that the iniatial get request does not execute an empty search
    if !params[:q].blank?  || !params[:page].blank? 
        params[:page] = params[:page] || 1
        @videos= []
        videos = Yt::Collections::Videos.new
        videos.where(q: params[:q], order: 'relevance', )
        videos.each do |v|
          @videos<<v
        end
        number_of_pages= @videos.size >= 300? 300 : @videos.size
        
        @page = WillPaginate::Collection.create(params[:page], 30, number_of_pages) do |pager|
          pager.replace @videos[pager.offset, 30]
         end
     end
  end


  def show
  		@video = Yt::Video.new id: params[:content_item_id]
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def index
		@public_notes = Note.where(user_id: current_user.id, public: true)
		@private_notes= Note.where(user_id: current_user.id, public: false)
	end

	def show
		@note= Note.find(params[:id])
		@note_video=  Yt::Video.new id: @note.content_item_id
		@note.increment(:views, by = 1).save
	end

	def new
		@note= Note.new
	end

	def create
		@note= Note.new(note_params)

		if @note.save
			redirect_to @note
		else
			redirect_to "content_items/search?content_item_id=#{params[:content_item_id]}"
		end
	end

	def edit

	end

	def update
		@note= Note.find(params[:id])
		@note.update(note_params)
	# if ok
	    respond_to do |format|
	      format.json {render json: {"status" => 200, :data => {title: @note.title, content: @note.content} }}
	    end
	 # if something goes wrong: fail the Ajax call
		rescue Exception => e
		  puts "Exception #{e.message}"
		  render :nothing => true, :status => 500
		
	end


	def destroy
		Note.find(params[:id]).destroy
		redirect_to notes_path
	end



	private

	def find_note

	end

	def note_params
		params.require(:note).permit(:title,:content,:user_id,:content_item_id, :public)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user= User.find_by(email: params[:session][:email].downcase)
  	# an object that isnt nil is true in a boolean context, which is
  	# why we can write this conditional statement
  	if user && user.authenticate(params[:session][:password])
      log_in(user)
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  	params[:page] = params[:page] || 1
 	@home_notes = Note.where(public: true).paginate(page: params[:page], per_page: 9).order('views DESC')
 	
 	respond_to do |format|
	  format.html
	  format.js
	end
  end

  def help
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
	@users= User.all.order('name ASC')
end

def new
	@user= User.new
end

def show
	@user= User.find(params[:id])
	@top_notes=  Note.where(user_id: @user.id, public: true).limit(5);
end

def create 
	@user= User.new(user_params)
  	if @user.save
  	  log_in @user
  	  redirect_to @user
      #same as redirect_to user_url(@user)
      flash[:success] = 'Welcome to YouNote!'
  	else
  	  render 'new'
    end

end

def public_notes
	@user= User.find(params[:id])
	@public_notes= @user.notes.where(public: true)
end

def edit 
  @user= User.find(params[:id])
end

def update
	@user= User.find(params[:id])
	if @user.update_attribute(:bio, params[:user][:bio])
	  flash[:success] = "Bio updated"
      redirect_to @user
    else
      render 'edit'
    end
end


private

 def user_params
	  params.require(:user).permit(:name, :email, :password, :password_confirmation, :bio)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper


	def full_title(page_title='')
		base_title= "YouNote"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end

end

app/helpers/content_items_helper.rb
module ContentItemsHelper
end

app/helpers/notes_helper.rb
module NotesHelper


	def note_public?
		Note.where(id: params[:id]).first.public
	end

	def user_of_note(note)
		name = User.find(note.user_id).name
	end

	def note_video_url(note)
		video= Yt::Video.new id: note.content_item_id
		video.thumbnail_url
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id]= user.id
	end

		# Remembers a user in a persistent session.
	  def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
	  end

	def current_user
		#user_id = session[:user_id] is not actually a comparison,
		#but an assinment, if session[:user_id] exists.
		if (user_id = session[:user_id])
	      @current_user ||= User.find_by(id: user_id)
	    elsif (user_id = cookies.signed[:user_id])
	      user = User.find_by(id: user_id)
	      if user && user.authenticated?(cookies[:remember_token])
	        log_in user
	        @current_user = user
	    	end
	    end
	end

	def logged_in?
		!current_user.nil?
	end

	def forget(user)
	    user.forget
	    cookies.delete(:user_id)
	    cookies.delete(:remember_token)
  	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user= nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
require 'net/http'

module UsersHelper

	def gravatar_for(user)
		if(gravatar?(user) )
			gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    		image_tag(gravatar_url, alt: user.name, class: "gravatar")
    	else
    		image_tag("profile-default.png", alt: user.name, title: "Create a Gravatar to display a cusom photo")
		end
	end

	private

	def gravatar?(user)
	    gravatar_check = "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email.downcase)}.png?d=404"
	    uri = URI.parse(gravatar_check)
	    http = Net::HTTP.new(uri.host, uri.port)
	    request = Net::HTTP::Get.new(uri.request_uri)
	    response = http.request(request)
	    response.code.to_i != 404 # from d=404 parameter
	end

	def is_logged_in?(user)
		current_user.id == user.id
	end


end

app/views/content_items/search.html.erb
<div class=" container search-partial">
	<h1>Search For Videos</h1>

	 <form method="post" action="search">
        <input type="text" name="q" size="31" value= "<%= params[:q] %>" autofocus>
        <input type="submit" value="Submit" class="search-bar">
 	</form>
</div>


<% if params[:q] %>

 	<div class="search-video-container">


	<%	@page.in_groups_of(3).each do |group| %>
			<div class="row">
				<% group.each do |video| %>
						<% if video %>
							<div class="col-md-4 thumbnail-item">
							    <%= link_to image_tag("#{video.thumbnail_url}", :size => "180x135"), {:action => 'show', :content_item_id => video.id} %>
							    <br>
							    <%= link_to video.title, {:action => 'show', :content_item_id => video.id} %> 
							</div>
						<% end %>
					<% end %>
			</div>	
		<% end %>
	</div>
		<%= will_paginate @page, :params => { :q => params[:q] } %>
<% end %>

app/views/content_items/show.html.erb
<div class="container show-container">
	<h1><%= @video.title %></h1>
	<div class="show-video-container container-fluid">
		<iframe width="640" height="360" src="https://www.youtube.com/embed/<%= @video.id %>" frameborder="0" allowfullscreen></iframe>
	</div>
	<div class="description container-fluid">
		<%= @video.description %>
	</div>

	<% if logged_in? %>
		<%= button_to "Create Note", new_note_url, :method => :get, :params => {title: "#{@video.title}", content_item_id: "#{@video.id}"}, :class => "btn btn-default btn-block" %>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container" style="height:50px;"></div>

<footer class="footer">
  <small>
    YouNote By <a href="http://tylergaugler16.github.io/">Tyler Gaugler</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" id="custom-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to "YouNote",   root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",   root_path %> </li>
        <li><%= link_to "Search",'/content_items/search' %>  </li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "My Notes", notes_path %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>

        <% else %>
        <li> <%= link_to login_path do  %>
              <span class="glyphicon glyphicon-log-in"></span> Login
             <% end %>
        </li>
        <li> <%= link_to "/signup" do  %>
              <span class="glyphicon glyphicon-user"></span> Sign Up
             <% end %>
        </li>
      <% end %>

      </ul>
    </div>
  </div>
</nav>

<!-- <div class="container space" style="height:50px;"></div> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>

    <%= render 'layouts/header' %>
    
    <div class="container">

      <!-- this is to display appropraite messages from the hash called flash.
        the loop adds the correct class to the div and displays the correct message
        (look at user/create method for example)-->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>    
    
  </body>

</body>
</html>

app/views/notes/_editableNote.html.erb
<div class="row">
	  <div class="col-md-12">
	  	<%= form_for @note, :remote => true, :url => {:controller => "notes", :action => "update"} do |f| %>
	     
	     
	      
	      <div id="note-content" contenteditable>
	      	<%= (@note.content != nil)? @note.content.html_safe : @note.content %>
	      </div>
			<div class="edit-options row">
				<div class="col-md-3">
					<select id= "font-size">
						<option value="14" selected> Font Size </option>
						<% [12,14,16,18,20].each do |num| %>
					     <option value="<%= num %>"><%= num %></option>
					    <% end %>
					</select>
				</div>
				<div class="col-md-1">
					<button id="embolden" class="btn btn-default btn-group-xs"><span class="glyphicon glyphicon-bold"></span></button>	
				</div>
				<div class="col-md-1">
					<button id="italicize" class="btn btn-default btn-group-xs"><span class="glyphicon glyphicon-italic"></span></button>	
				</div>
				<div class="col-md-1">
					<button id="underline" class="btn btn-default btn-group-xs"><span><b>U</b></span></button>
				</div>
				<div class="col-md-6">
					<button id="create-table" class="btn btn-default btn-group-xs"><span>Create Table</span></button>
					<input type="text" id ="table-rows" placeholder="rows">
					<input type="text" id ="table-columns" placeholder="columns">
				</div>
				
			</div>
		
	      <%= f.submit "Update Note", class: "btn btn-primary update-note" %>

		<% end %>
	  </div>

	  

	</div>

app/views/notes/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@note) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', value: params[:title] %>

      <%= f.hidden_field :user_id, class: 'form-control', value: current_user.id  %>
      <%= f.hidden_field :content_item_id, class: 'form-control', value: params[:content_item_id]  %>
      <%= f.hidden_field :public, class: 'form-control', value: 'false' %>

      <%= f.submit "Create my Note", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/notes/_uneditableNote.html.erb
<div class="row">
		<div class="col-md-12 ">
			<div class="uneditable-note">
				<%= @note.content.html_safe %>
			</div>
			
		</div>
</div>

app/views/notes/index.html.erb
<h1> My Notes</h1>


<div class="panel panel-default">
    <div class="panel-heading">
    	<span> <b>Public Notes</b> <span class="badge"><%= @public_notes.size %></span ></span><br>
    </div>
    <% @public_notes.each do |note| %>
    	<div class="panel-body"> <%= link_to note.title, note %> </div>
    <% end %>
</div>

<br>

<div class="panel panel-default">
    <div class="panel-heading">
    	<span><b>Private Notes</b><span class="badge"><%= @private_notes.size %></span ></span><br>
    </div>
    <% @private_notes.each do |note| %>
    	<div class="panel-body"> <%= link_to note.title, note %> </div>
    <% end %>
</div>

app/views/notes/new.html.erb
<div class="note_form_container container">
	<h1>Name Your New Note</h1>
	
	<%= render 'notes/form' %>
</div>

app/views/notes/show.html.erb
<div class="note-container container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div id="note-info">
				<span id="author"> Note Author: <%= link_to user_of_note(@note), user_path(@note.user_id) %> </span>
				<span id="views"> Views:  <%= @note.views %> </span>
			</div>
		</div>
	</div>

	
		 <h1 class="note-title-header"> <span <%= ((current_user) && @note.user_id == current_user.id)?  "contenteditable=true" : '' %> > <%= @note.title %> </span></h1>
	<div class="row">
		<div class="col-md-6">
			<div class="show-video-container container-fluid">
				<iframe width="608" height="342" src="https://www.youtube.com/embed/<%= @note_video.id %>" frameborder="0" allowfullscreen></iframe>
			</div>
			<button class="btn btn-default btn-xs" id='hide-description'><span class="glyphicon glyphicon-minus"></span>
			</button>
			<span id="description-message">Hide Description</span>
			<div class="description container-fluid">
				<%= @note_video.description %>
			</div>
			
		</div>
		<div class="col-md-6">
			<% if ((current_user) && @note.user_id == current_user.id) %>	
				<%= render 'editableNote' %>
			<% else %>
				<%= render 'uneditableNote' %>
			<% end %>
		</div>
	</div>

<% if current_user && @note.user_id == current_user.id  %>
	<div class="row">
		<div class="col-md-12" id="note-settings-block">
	  	<button class="btn btn-default btn-sm" id='hide-note-settings'><span class="glyphicon glyphicon-warning-sign"></span>
	  	<span id="note-settings-label"> Settings </span>
	   </button>
	   
	  </div>
	</div>

	<div class="row">
		<div class="col-md-6 note-settings" id="" style= "display:none;" >
				<span> <input type="checkbox" name="public" value="publics" id="public-checkbox" <%= (@note.public?)? "checked": "" %>> </span>
	  			<span>Make Your Note Public to All Users</span> <br>
	  			<span class="glyphicon glyphicon-ok" <%= (@note.public?)? "style= visibility:visible" : "style= visibility:hidden" %> id='check-for-public'></span>
	  			<span <%= (note_public?)? "style= visibility:visible" : "style= visibility:hidden" %> id='message-for-public'>Your Note is Public for all Users to see!</span>
	  		
		</div>

		<div class="col-md-6 note-settings" style= 'display:none;'>
			<span><b>Warning: This Will Permanently Delete Your Note</b></span> <br>
			<%= button_to 'Delete Note', @note, :method => :delete, :params =>{ id: @note.id}, :class => "btn btn-default btn-block ", :id=> 'delete-note-button' , :onclick => "return confirm('Are You Sure You Want to Delete Your Note?');" %>
		</div>

	</div>

		
<% end %>

		
	


</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_home_notes.html.erb
<%	@home_notes.in_groups_of(3).each do |group| %>
			<div class="row">
				<% group.each do |note| %>
						<% if note %>
							<div class="col-md-4 home-note">
							    <h2> <%= link_to note.title, note_path(note) %> </h2>
							    <br>
							 	<%= link_to image_tag(note_video_url(note), :size => "200x150"), note_path(note) %>
							    <h2> By <%= link_to user_of_note(note), user_path(note.user_id) %> </h2>
							</div>
						<% end %>
					<% end %>
			</div>	
		<% end %>

app/views/static_pages/help.html.erb
<h1>Help</h1>

<p>For source code of YouNote visit <a href="https://github.com/tylergaugler16/youNote">here</a></p>

app/views/static_pages/home.html.erb
<div class="container home-picture">
	<h1 id="white-font">Welcome to YouNote!</h1>
	<p class="center">Search for videos on Youtube and take notes while watching. Save them so you can come back to them later. </p>
	<span><%= link_to 'Sign Up Now!', '/signup' %> </span>
</div>

<div class="container">
	<%= button_to "Search For Videos", {controller: "content_items", action: "search"},  {id: "search-button"} %>
</div>

<div id="gray-line-break">
	<span id="home-notes-title">Popular Notes</span>
</div>

<div id="my-notes">
  <%= render 'home_notes', object: @home_notes %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @home_notes %>
</div>

<div id="ajax-gif"></div>

app/views/static_pages/home.js.erb
$('#my-notes').append("<%= j render 'home_notes', object: @home_notes %>");
<% if @home_notes.next_page %>
	console.log("there is a next page");
  $('.pagination').replaceWith('<%= j will_paginate @home_notes %>');
  $('.pagination').css('display','none');
<% else %>
  $(window).off('scroll');
  $('#ajax-gif').css('display', 'none');
  $('.pagination').remove();
<% end %>

app/views/users/edit.html.erb
<h1 class="left-header"> Edit Profile </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :bio %>
      <%= f.text_area :bio, value: @user.bio , rows: 10, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<div class="container-fluid user_list">

	<h1>Users List</h1>

	<% @users.each.with_index do |user,index| %>
		<div class="panel-group">
		  <div class="panel panel-default">
		    <div class="panel-heading">
		      <h4 class="panel-title">
		        <a data-toggle="collapse" href="#collapse<%= index %>" <%= ((current_user) && user.id == current_user.id)? "style=color:#2bb0ff" : "" %>> <%= user.name %> </a>
		      </h4>
		    </div>

		    <div id="collapse<%= index %>" class="panel-collapse collapse">
		      <div class="panel-body">Number of Notes: <%= user.notes.size %> </div>
		      <div class="panel-footer"> <%= link_to 'View Profile', user  %> </div>
		    </div>
		  </div>
		</div>

	 <% end %> 

	

</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/public_notes.html.erb
<h1> <%= @user.name %>'s notes </h1>


<div class="panel panel-default">
    <div class="panel-heading">
    	<span> <b>Public Notes</b> <span class="badge"><%= @public_notes.size %></span ></span><br>
    </div>
    <% @public_notes.each do |note| %>
    	<div class="panel-body"> <%= link_to note.title, note %> </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	
<div class="row user_info">
	<div class="col-md-3">
		<div class= "container-fluid profile-picture">
				<%= gravatar_for @user %>
  		</div>
  		<p><%= @user.email %></p>
  		<% if ( (current_user) && current_user.id == @user.id )%>
			<%= link_to "View All My Notes", notes_path %> <br> 
			<%= link_to "Update My Profile", edit_user_path(current_user) %> <br>
			<div class="container">
				<%= link_to ("Search For Videos <span class='glyphicon glyphicon-search'></span>").html_safe, {controller: "content_items", action: "search"}%>
			</div>
		<% else %>
			<%= link_to "View Public Notes", controller: "users", action: "public_notes" ,params: {id: @user.id} %>
		<% end %>
	</div>

	<div class="col-md-8">
			<h1> <%= @user.name %> </h1>
			
			<div class="container-fluid user-bio">
					<%= @user.bio %>
			</div>
	
	</div>
</div>

<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-8">
		<div class="top_notes container-fluid">
				  <div class="panel panel-default">
				    <div class="panel-heading">
				    	<span class="left">Top Public Notes</span>
				    	<span class="right">Total Number of Notes: <%= @user.notes.size %> </span>
				    </div>
				    <% @top_notes.each do |note| %>
				    	<div class="panel-body"> <%= link_to note.title, note %> </div>
				    <% end %>
				  </div>
			</div>
	</div>	
</div>



</div>